name: Check Helm Release

on: [push]

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Kubernetes context
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Check Helm release status
      run: |
        helm status RELEASE_NAME -n NAMESPACE
