name: Check Helm Release

on: [push]

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Kubernetes context
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'
    - name: Set Helm Home
      run: echo "HELM_HOME=$HOME/.config/helm" >> $GITHUB_ENV
    - name: Install Helm Diff plugin
      run: helm plugin install https://github.com/databus23/helm-diff

    - name: Check Helm release status
      run: |
        helm ls -n default
        helm diff upgrade -h
